### ISSUE TITLE
Feature request with Geoip

### ISSUE THREAD

**Issue by skoky** [erichutchins/polars_iptools#9]
Can you advice how to extract `asnorg` and `country` from geoip? There are function asn and full only. Its not easy to parse the full's response in polars, or is it? Thanks

**Comment by skoky** [comment]
I found the `struct` I can parse from the `full` method. Its good enough. Thanks.

**Comment by erichutchins** [comment]
Thanks for checking out the plugin! Feedback welcomed how to make it easiest to use. Maybe more python interfacing to simplify the struct parsing?
